class TREE_CLASS;
class FRUIT_CLASS;
class BRANCH_CLASS{
private:
    unsigned int fruitTotal;
    unsigned int weightTotal;
    unsigned int growthHeight;
    unsigned int branchLength;
    FRUIT_CLASS* last;
    FRUIT_CLASS* head;
    TREE_CLASS* whichTree;
    BRANCH_CLASS* next;
    BRANCH_CLASS* prev;
public:
    void displayAll();
    BRANCH_CLASS();
    BRANCH_CLASS(TREE_CLASS*, unsigned int);
    BRANCH_CLASS(const BRANCH_CLASS&);
    unsigned int getFruitsTotal(void);
    unsigned int getWeightsTotal(void);
    unsigned int getHeight(void);
    unsigned int getLength(void);
    void addFruit(unsigned int);
    void addWeight(unsigned int);
    void addHeight(unsigned int);
    void addLength(unsigned int);
    void decFruit(unsigned int);
    void decWeight(unsigned int);
    void decHeight(unsigned int);
    void decLength(unsigned int);
    void setTree(TREE_CLASS* );
    void setNext(BRANCH_CLASS*);
    void setPrev(BRANCH_CLASS*);
    BRANCH_CLASS * getNext(void);
    BRANCH_CLASS* getPrev(void);
    void growthBranch(void);
    void fadeBranch(void);
    void harvestBranch(unsigned int);
    void cutBranch(unsigned int);
    FRUIT_CLASS* getFruitPointer(unsigned int);
    TREE_CLASS* getTreePointer(void);
    //void display(void);
    ~BRANCH_CLASS();
    void setHeight(unsigned int);
};
